version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: restoran_db
    environment:
      POSTGRES_USER: restoran
      POSTGRES_PASSWORD: restoran123
      POSTGRES_DB: restoran_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: